routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function() {
	Route::get('/', [
        'as' => 'admin', 'uses' => 'Admin@index','middleware' => 'auth' 
    ]);
    Route::get('/masjid', [
        'as' => 'masjid', 'uses' => 'Masjid@index','middleware' => 'auth' 
    ]);
    Route::get('/masjid/create', [
        'as' => 'add-masjid', 'uses' => 'Masjid@create','middleware' => 'auth' 
    ]);
    Route::post('/masjid', [
        'as' => 'save-masjid', 'uses' => 'Masjid@store','middleware' => 'auth' 
    ]);
    Route::get('/masjid/{id}/edit', [
        'as' => 'masjid.edit', 'uses' => 'Masjid@edit','middleware' => 'auth' 
    ]);
    Route::patch('/masjid/{id}', [
        'as' => 'update.masjid', 'uses' => 'Masjid@update','middleware' => 'auth' 
    ]);
    Route::get('/masjid/{id}', [
        'as' => 'masjid.show', 'uses' => 'Masjid@show','middleware' => 'auth' 
    ]);
    Route::delete('/masjid/{id}', [
        'as' => 'masjid.destroy', 'uses' => 'Masjid@destroy','middleware' => 'auth' 
    ]);
    Route::get('/jamaah', [
        'as' => 'masjid.jamaah', 'uses' => 'Masjid@jamaah','middleware' => 'auth' 
    ]);

    Route::resource('category', 'Category')->middleware('auth');;
    Route::resource('subcategory', 'SubCategory')->middleware('auth');;
    Route::resource('pembangunan', 'Pembangunan')->middleware('auth');;
    Route::resource('berita', 'Berita')->middleware('auth');;
    Route::resource('sejarah', 'Sejarah')->middleware('auth');;
    Route::resource('visimisi', 'VisiMisi')->middleware('auth');;
    Route::resource('dkm', 'Dkm')->middleware('auth');;
    Route::resource('page', 'Page')->middleware('auth');;
    Route::resource('team', 'Team')->middleware('auth');;
    Route::resource('donasimasjid', 'DonasiMasjid')->middleware('auth');;
    Route::resource('donasiyukamal', 'DonasiYukamal')->middleware('auth');;
    Route::resource('pengguna', 'Pengguna')->middleware('auth');;
    Route::resource('keuangan', 'MasjidFinance')->middleware('auth');;
    Route::resource('pembangunan_masjid', 'PembangunanMasjid')->middleware('auth');;
    Route::resource('event', 'Event')->middleware('auth');;
    Route::resource('galeri', 'Galeri')->middleware('auth');;
    Route::resource('profilpengguna', 'Profil')->middleware('auth');;
    Route::get('/profilpengguna/{id}/changepassword', [
        'as' => 'profilpengguna.password', 'uses' => 'Profil@password','middleware' => 'auth' 
    ]);
    Route::patch('/profilpengguna/{id}/updatepassword', [
        'as' => 'profilpengguna.updatepassword', 'uses' => 'Profil@update_password','middleware' => 'auth' 
    ]);

    Route::resource('masjid_account', 'MasjidAccount')->middleware('auth');;
    Route::resource('useryukamal', 'UserYukamal')->middleware('auth');;
    Route::resource('provinsi', 'Provinsi')->middleware('auth');;
    Route::resource('kota', 'Kota')->middleware('auth');;
    Route::resource('kecamatan', 'Kecamatan')->middleware('auth');;
    Route::resource('kelurahan', 'Kelurahan')->middleware('auth');;
});

Route::group(['prefix' => '/'], function() {
    Route::get('/', [
        'as' => 'home', 'uses' => 'HomeController@index' 
    ]);
    Route::get('/donasi', [
        'as' => 'donasi', 'uses' => 'HomeController@donasi' 
    ]);
    Route::post('/donasi-search', [
        'as' => 'donasi-search', 'uses' => 'HomeController@donasi' 
    ]);
    Route::get('/detail/{id}', [
        'as' => 'detail', 'uses' => 'HomeController@detail' 
    ]);
    Route::get('/detailberita/{id}', [
        'as' => 'detailberita', 'uses' => 'HomeController@detailberita' 
    ]);
    Route::get('/detailacara/{id}', [
        'as' => 'detailacara', 'uses' => 'HomeController@detailacara' 
    ]);
    Route::get('/proses/{id}', [
        'as' => 'proses', 'uses' => 'HomeController@proses' 
    ]);
    Route::post('/proses', [
        'as' => 'proses-donasi', 'uses' => 'HomeController@store'
    ]);
    Route::get('/payment/{id}', [
        'as' => 'payment', 'uses' => 'HomeController@payment'
    ]);
    Route::post('/payment', [
        'as' => 'updatepic', 'uses' => 'HomeController@fileupload'
    ]);
    Route::get('/berita', [
        'as' => 'berita', 'uses' => 'HomeController@berita' 
    ]);
    Route::get('/acara', [
        'as' => 'acara', 'uses' => 'HomeController@acara' 
    ]);
    Route::post('/acara-search', [
        'as' => 'acara-search', 'uses' => 'HomeController@acara' 
    ]);
    Route::get('/about', [
        'as' => 'about', 'uses' => 'HomeController@about' 
    ]);
    Route::get('/profile', [
        'as' => 'profile', 'uses' => 'HomeController@profile' 
    ]);
    Route::get('/forgot_password', [
        'as' => 'forgot_password', 'uses' => 'HomeController@forgot_password' 
    ]);
    Route::get('/mytransaction', [
        'as' => 'mytransaction', 'uses' => 'HomeController@mytransaction' 
    ]);
    Route::get('/register_user', [
        'as' => 'register_user', 'uses' => 'HomeController@register' 
    ]);
    Route::post('/create_user', [
        'as' => 'create_user', 'uses' => 'SocialAuth@create_user'
    ]);
    Route::post('/update_profile', [
        'as' => 'update_profile', 'uses' => 'HomeController@update_profile'
    ]);
    Route::post('/update_password', [
        'as' => 'update_password', 'uses' => 'HomeController@update_password'
    ]);
    Route::post('/proses_password', [
        'as' => 'proses_password', 'uses' => 'HomeController@proses_password'
    ]);
    Route::post('/donasi_yukamal', [
        'as' => 'donasi_yukamal', 'uses' => 'HomeController@donasi_yukamal'
    ]);
    Route::get('/cancel/{id}', [
        'as' => 'cancel', 'uses' => 'HomeController@cancel'
    ]);
    Route::get('auth/{provider}', 'SocialAuth@redirectToProvider');
    Route::get('auth/{provider}/callback', 'SocialAuth@handleProviderCallback');
    Route::get('/detail/{id}/export-excel-finance/', [
        'as' => 'export-excel-finance', 'uses' => 'HomeController@export_excel_finance'
    ]);
    Route::get('/detail/{id}/export-pdf-finance/', [
        'as' => 'export-pdf-finance', 'uses' => 'HomeController@export_pdf_finance'
    ]);
});

Route::get('/get_subcategory/{id}', ['as' => 'get-subcategory', 'uses' => 'SubCategory@getSubCategory']);
Route::get('/city/{id}', ['as' => 'get-city', 'uses' => 'Area@getCity']);
Route::get('/districts/{id}', ['as' => 'get-districts', 'uses' => 'Area@getDisctricts']);
Route::get('/alldistricts', ['as' => 'get-all-districts', 'uses' => 'Area@getAllDisctricts']);
Route::get('/villages/{id}', ['as' => 'get-villages', 'uses' => 'Area@getVillages']);
Route::get('/allvillages', ['as' => 'get-all-villages', 'uses' => 'Area@getAllVillages']);

Auth::routes();

// Route::get('/', 'HomeController@index')->name('home');

// ini bua frontend
Route::get('/getmasjid', ['as' => 'get-masjid', 'uses' => 'Masjid@getMasjid']);
Route::get('/getmasjid/{id}', ['as' => 'get_masjid_by_id', 'uses' => 'Masjid@getMasjid']);

resources/views/backend/admin/category_edit.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
	    <h1 class="page-title">Edit Kategori</h1>
	    <!-- INPUT CONTENT BELOW HERE -->
        <div class="portlet-body form">
            <form role="form" method="post" action="{{ route('category.update', $data->id) }}">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="form-body">
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" class="form-control" id="form_control_1" value="{{$data->nama}}" name="nama" maxlength="45">
                        <label for="form_control_1">Nama Kategori</label>
                    </div>
                </div>
                <div class="form-actions noborder">
                    <button type="submit" class="btn blue">Submit</button>
                    <a href="{{route('category.index')}}"><button type="button" class="btn default">Cancel</button></a>
                </div>
            </form>
        </div>
		<!-- FINISH HERE -->
	</div>
</div>
<!-- END CONTENT -->

resources/views/backend/admin/donasiyukamal_edit.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
	    <h1 class="page-title">Donasi YukAmal</h1>
	    <!-- INPUT CONTENT BELOW HERE -->
        <div class="portlet-body form">
            <form role="form" method="post" enctype="multipart/form-data" action="{{ route('donasiyukamal.update', $data->id) }}">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="form-body">
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" class="form-control" id="form_control_1" value="{{$data->no_trans}}" name="no_trans" disabled>
                        <label for="form_control_1">Nomor Transaksi</label>
                    </div>
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" class="form-control" id="form_control_1" value="{{date('d/m/Y', strtotime($data->date))}}" name="date" disabled>
                        <label for="form_control_1">Tanggal</label>
                    </div>
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" class="form-control" id="form_control_1" value="{{$data->contributor_name}}" name="contributor_name" disabled>
                        <label for="form_control_1">Nama Donatur</label>
                    </div>
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" class="form-control" id="form_control_1" value="{{number_format($data->nominal,2,',','.')}}" name="nominal" disabled>
                        <label for="form_control_1">Nominal</label>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Foto</label><br>
                        <div class="fileinput {{is_null($data->pic) ? 'fileinput-new' : 'fileinput-exist'}}" data-provides="fileinput">
                            <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                @if(!is_null($data->pic))
                                <img src="{{url('uploads/'.$data->pic)}}">
                                @endif
                            </div>
                            <div>
                                <span class="btn red btn-outline btn-file">
                                    <span class="fileinput-new"> Select image </span>
                                    <span class="fileinput-exists"> Change </span>
                                    <input type="file" name="image"> </span>
                                <a href="javascript:;" class="btn red fileinput-exists" onClick="remove()" data-dismiss="fileinput"> Remove </a>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" class="form-control" id="image_old" value="{{$data->pic}}" name="image_old" maxlength="255">
                    <input type="hidden" class="form-control" id="image_name" value="{{$data->pic}}" name="image_name" maxlength="255">
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <select class="form-control edited" name="status">
                            <option value="0" {{$data->status == '0' ? 'selected' : ''}}>Proses</option>
                            <option value="1" {{$data->status == '1' ? 'selected' : ''}}>Gagal</option>
                            <option value="2" {{$data->status == '2' ? 'selected' : ''}}>Sukses</option>
                        </select>
                        <label for="status">Status</label>
                    </div>
                </div>
                <div class="form-actions noborder">
                    <button type="submit" class="btn blue">Submit</button>
                    <a href="{{route('donasiyukamal.index')}}"><button type="button" class="btn default">Cancel</button></a>
                </div>
            </form>
        </div>
		<!-- FINISH HERE -->
	</div>
</div>
<!-- END CONTENT -->
<script>
  function remove(){
    document.getElementById("image_old").value = "";
  }
</script>

resources/views/backend/admin/email_donasi_masjid.blade.php
<!DOCTYPE html>
<html>
<body>
	Ini adalah Body Email Donasi Masjid.
</body>
</html>

resources/views/backend/admin/galeri_show.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
	    <h1 class="page-title">Detail Galeri</h1>
	    <!-- INPUT CONTENT BELOW HERE -->
        <div class="portlet-body form">
            <div class="form-body">
                <a href="{{route('galeri.edit', $data->id)}}"><button type="button" class="btn blue">Update</button></a>
                <a data-target="#static-{{$data->id}}" id="modal_delete" data-id="{{$data->id}}" data-toggle="modal"><button type="button" class="btn red">Delete</button></a>
                <div id="static-{{$data->id}}" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
                    <form method="post" action="{{route('galeri.destroy', $data->id)}}">
                    {{ method_field('DELETE') }}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    
                    <div class="modal-body">
                        <p> Apakah Anda yakin ini menghapus? </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                        <button type="submit"  class="btn red">Delete</button>
                    </div>
                    </form>
                </div>
                <br><br>
                <table class="table">
                    <tbody>
                        <tr>
                            <th width="150">Masjid</th>
                            <td width="30">:</td>
                            <td>
                                @foreach($masjid as $m)
                                @if($m->id == $data->mosque_id)
                                    {{$m->name}}
                                @endif
                                @endforeach
                            </td>
                        </tr>
                        <tr>
                            <th>Deskripsi</th>
                            <td>:</td>
                            <td><?= $data->description;?></td>
                        </tr>
                        <tr>
                            <th>Foto</th>
                            <td>:</td>
                            <td><img style="width: 360px; height: 270px;" src="{{url('uploads/'.$data->pic)}}"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="form-actions noborder">
                <a href="{{route('galeri.index')}}"><button type="button" class="btn default">Cancel</button></a>
            </div>
        </div>
		<!-- FINISH HERE -->
	</div>
</div>
<!-- END CONTENT -->
<script src="{{url('/')}}/ckeditor/ckeditor.js" type="text/javascript"></script>
<script>
  var textarea = document.getElementById("description");
    CKEDITOR.replace(textarea,{
    language:'en-gb'
  });
  CKEDITOR.config.allowedContent = true;
</script>

resources/views/backend/admin/kota.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
	    <h1 class="page-title"> Kota</h1>
	    <!-- INPUT CONTENT BELOW HERE -->
        @if(session()->has('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
        @if(session()->has('alert'))
            <div class="alert alert-danger">
                {{ session()->get('alert') }}
            </div>
        @endif
		<div class="portlet-body">
            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                <thead>
                    <tr>
                        <td align="center" class="bold" width="40%"> Nama </td>
                        <td align="center" class="bold"> Provinsi </td>
                        <td align="center" class="bold"> Actions </td>
                    </tr>
                </thead>
                <tbody>
                	@foreach($data as $val)
                    <tr class="odd gradeX">
                        <td align="left"> {{$val->name}} </td>
                        @foreach($province as $prov)
                        @if($prov->id == $val->province_id)
                        <td align="left"> {{$prov->name}} </td>
                        @endif
                        @endforeach
                        <td align="center">
                            <a href="{{route('kota.show', $val->id)}}"><i class="fa fa-eye"></i></a> |
                            <a href="{{route('kota.edit', $val->id)}}"><i class="fa fa-pencil"></i></a> |
                            <a data-target="#static-{{$val->id}}" id="modal_delete" data-id="{{$val->id}}" data-toggle="modal"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <div id="static-{{$val->id}}" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
                        <form method="post" action="{{route('kota.destroy', $val->id)}}">
                        {{ method_field('DELETE') }}
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        
                        <div class="modal-body">
                            <p> Apakah Anda yakin ini menghapus? </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                            <button type="submit"  class="btn red">Delete</button>
                        </div>
                        </form>
                    </div>
                    @endforeach
                </tbody>
            </table>
        </div>
		<!-- FINISH HERE -->
	</div>
</div>
<!-- END CONTENT -->

resources/views/backend/admin/kota_show.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title">Detail Kota</h1>
        <!-- INPUT CONTENT BELOW HERE -->
        <div class="portlet-body form">
            <div class="form-body">
                <a href="{{route('kota.edit', $data->id)}}"><button type="button" class="btn blue">Update</button></a>
                <a data-target="#static-{{$data->id}}" id="modal_delete" data-id="{{$data->id}}" data-toggle="modal"><button type="button" class="btn red">Delete</button></a>
                <div id="static-{{$data->id}}" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
                    <form method="post" action="{{route('kota.destroy', $data->id)}}">
                    {{ method_field('DELETE') }}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    
                    <div class="modal-body">
                        <p> Apakah Anda yakin ini menghapus? </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                        <button type="submit"  class="btn red">Delete</button>
                    </div>
                    </form>
                </div>
                <br><br>
                <table class="table">
                    <tbody>
                        <tr>
                            <th width="150">Provinsi</th>
                            <td width="30">:</td>
                            @foreach($province as $p)
                            @if($p->id == $data->province_id)
                            <td>{{$p->name}}</td>
                            @endif
                            @endforeach
                        </tr>
                        <tr>
                            <th>Nama</th>
                            <td>:</td>
                            <td>{{$data->name}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="form-actions noborder">
                <a href="{{route('kota.index')}}"><button type="button" class="btn default">Cancel</button></a>
            </div>
        </div>
        <!-- FINISH HERE -->
    </div>
</div>
<!-- END CONTENT -->

resources/views/backend/admin/provinsi.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
	    <h1 class="page-title"> Provinsi</h1>
	    <!-- INPUT CONTENT BELOW HERE -->
        @if(session()->has('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
        @if(session()->has('alert'))
            <div class="alert alert-danger">
                {{ session()->get('alert') }}
            </div>
        @endif
		<div class="portlet-body">
            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                <thead>
                    <tr>
                        <td align="center" class="bold"> Nama </td>
                        <td align="center" class="bold"> Actions </td>
                    </tr>
                </thead>
                <tbody>
                	@foreach($data as $val)
                    <tr class="odd gradeX">
                        <td align="left"> {{$val->name}} </td>
                        <td align="center">
                            <a href="{{route('provinsi.show', $val->id)}}"><i class="fa fa-eye"></i></a> |
                            <a href="{{route('provinsi.edit', $val->id)}}"><i class="fa fa-pencil"></i></a> |
                            <a data-target="#static-{{$val->id}}" id="modal_delete" data-id="{{$val->id}}" data-toggle="modal"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <div id="static-{{$val->id}}" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
                        <form method="post" action="{{route('provinsi.destroy', $val->id)}}">
                        {{ method_field('DELETE') }}
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        
                        <div class="modal-body">
                            <p> Apakah Anda yakin ini menghapus? </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                            <button type="submit"  class="btn red">Delete</button>
                        </div>
                        </form>
                    </div>
                    @endforeach
                </tbody>
            </table>
        </div>
		<!-- FINISH HERE -->
	</div>
</div>
<!-- END CONTENT -->

resources/views/backend/admin/subcategory.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
	    <h1 class="page-title"> Sub Kategori </h1>
	    <!-- INPUT CONTENT BELOW HERE -->
        @if(session()->has('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
        @if(session()->has('alert'))
            <div class="alert alert-danger">
                {{ session()->get('alert') }}
            </div>
        @endif
		<div class="portlet-body">
            <div class="table-toolbar">
                <div class="row">
                    <div class="col-md-6">
                        <div class="btn-group">
                            <a href="{{ route('subcategory.create') }}">
                                <button class="btn sbold green"> Add New
                                    <i class="fa fa-plus"></i>
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                <thead>
                    <tr>
                        <td align="center" class="bold"> Nama </td>
                        <td align="center" class="bold"> Tipe </td>
                        <td align="center" class="bold"> Actions </td>
                    </tr>
                </thead>
                <tbody>
                	@foreach($data as $val)
                    <tr class="odd gradeX">
                        <td align="left"> {{$val->category_name}} </td>
                        <td align="left"> {{$val->nama}} </td>
                        <td align="center">
                            <a href="{{route('subcategory.show', $val->id)}}"><i class="fa fa-eye"></i></a> |
                            <a href="{{route('subcategory.edit', $val->id)}}"><i class="fa fa-pencil"></i></a> | 
                            <a data-target="#static-{{$val->id}}" id="modal_delete" data-id="{{$val->id}}" data-toggle="modal"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <div id="static-{{$val->id}}" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
                        <form method="post" action="{{route('subcategory.destroy', $val->id)}}">
                        {{ method_field('DELETE') }}
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        
                        <div class="modal-body">
                            <p> Apakah Anda yakin ini menghapus? </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                            <button type="submit"  class="btn red">Delete</button>
                        </div>
                        </form>
                    </div>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- END CONTENT -->

resources/views/backend/admin/subcategory_create.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
	    <h1 class="page-title">Tambah Kategori</h1>
	    <!-- INPUT CONTENT BELOW HERE -->
        <div class="portlet-body form">
            <form role="form" method="post" action="{{ route('subcategory.store') }}">
                {{ csrf_field() }}
                <div class="form-body">
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <select class="form-control edited" name="category_id">
                            @foreach($category as $cat)
                            <option value="{{$cat->id}}">{{$cat->nama}}</option>
                            @endforeach
                        </select>
                        <label for="mosque">Kategori</label>
                    </div>
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" class="form-control" id="form_control_1" value="" name="nama" maxlength="45">
                        <label for="form_control_1">Nama Kategori</label>
                    </div>
                </div>
                <div class="form-actions noborder">
                    <button type="submit" class="btn blue">Submit</button>
                    <a href="{{route('subcategory.index')}}"><button type="button" class="btn default">Cancel</button></a>
                </div>
            </form>
        </div>
		<!-- FINISH HERE -->
	</div>
</div>
<!-- END CONTENT -->

resources/views/backend/admin/team_show.blade.php
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title">Detail Team</h1>
        <!-- INPUT CONTENT BELOW HERE -->
        <div class="portlet-body form">
            <div class="form-body">
                <a href="{{route('team.edit', $data->id)}}"><button type="button" class="btn blue">Update</button></a>
                <a data-target="#static-{{$data->id}}" id="modal_delete" data-id="{{$data->id}}" data-toggle="modal"><button type="button" class="btn red">Delete</button></a>
                <div id="static-{{$data->id}}" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
                    <form method="post" action="{{route('team.destroy', $data->id)}}">
                    {{ method_field('DELETE') }}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    
                    <div class="modal-body">
                        <p> Apakah Anda yakin ini menghapus? </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                        <button type="submit"  class="btn red">Delete</button>
                    </div>
                    </form>
                </div>
                <br><br>
                <table class="table">
                    <tbody>
                        <tr>
                            <th width="150">Foto</th>
                            <td width="30">:</td>
                            <td><img style="width: 360px; height: 270px;" src="{{url('uploads/'.$data->pic)}}"></td>
                        </tr>
                        <tr>
                            <th>Nama</th>
                            <td>:</td>
                            <td>{{$data->fullname}}</td>
                        </tr>
                        <tr>
                            <th>Jabatan</th>
                            <td>:</td>
                            <td>{{$data->position}}</td>
                        </tr>
                        <tr>
                            <th>Biografi</th>
                            <td>:</td>
                            <td><?= $data->biography;?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="form-actions noborder">
                <a href="{{route('team.index')}}"><button type="button" class="btn default">Back</button></a>
            </div>
        </div>
        <!-- FINISH HERE -->
    </div>
</div>
<!-- END CONTENT -->
<script src="{{url('/')}}/ckeditor/ckeditor.js" type="text/javascript"></script>
<script>
  var textarea = document.getElementById("description");
    CKEDITOR.replace(textarea,{
    language:'en-gb'
  });
  CKEDITOR.config.allowedContent = true;
</script>